name: Optimize
on:
  # Comment the next line if you don't want the Action to run on Pull Requests.
  workflow_dispatch:
  workflow_call:
  push:
  # Uncomment the next line if you want the Action to run on pushes.
  # Uncomment the next 2 lines if you want the Action to run on a schedule.
  #   schedule:
  #   - cron:  '0 * * * 1'  # See https://crontab.guru/
  # Uncomment 1 of the next 2 lines if you want to manually trigger the Action.
  #   repository_dispatch:
  #   workflow_dispatch:
permissions:
  contents: write

jobs:
  svgs:
    name: SVGs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      # Uncomment the next 2 lines to select a branch for schedule or dispatch.
      #   with:
      #     ref: main
      - uses: ericcornelissen/svgo-action@v3
        id: svgo
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{steps.svgo.outputs.DID_OPTIMIZE}}
        with:
          commit_message: Optimize ${{steps.svgo.outputs.OPTIMIZED_COUNT}} SVG(s)
